In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy as np


In [9]:
arr=np.random.randint(1, 50,size=(10))
arr


array([31, 16, 13, 16, 11, 21,  1, 48, 37, 32])

In [10]:
arr.ndim

1

In [16]:
arr.shape

(10,)

In [17]:
arr.size

10

In [18]:
arr=np.random.randint(10, 100,size=(2,5))
arr


array([[53, 79, 77, 55, 46],
       [32, 39, 58, 85, 58]])

In [19]:
arr.shape


(2, 5)

<h3>exercise 2</h3>

<h4> A. צרי מערך באורך 10 של מספרים שלמים רנדומליים בין 1 ל-50 וחשבי את הממוצע של המספרים</h4>

In [14]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array

array([31,  2, 30, 48,  4, 21, 24, 31, 15, 21])

<h4>B צרי שני מערכים דו מימדיים בגודל 3, חברי אותם, ובדקי מה הממוצע של התוצאה</h4>

In [15]:
a = np.array([[1, 2, 3],[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [17]:
b = np.array([[1, 2, 3],[4,5,6,],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

<h4> C. צרי מערך של 20 מספרים שלמים רנדומליים בין 1 ל-100. מצאי את כל המספרים שגדולים מ-50 במערך זה.</h4>

In [19]:
random_int_array2 = np.random.randint(1, 100, size=(20))
random_int_array2

array([25, 19, 58, 81, 81, 11, 50, 75, 24, 16, 87, 97, 50, 61, 30, 44, 33,
       42, 87, 20])

In [22]:
condition=random_int_array2>50
newArr=random_int_array2[condition]
newArr

array([58, 81, 81, 75, 87, 97, 61, 87])

<h4>D. צרי מערך של מספרים מ-1 עד 10. ערבבי את המערך ולאחר מכן בחרי באופן אקראי  אלמנטים ממנו </h4>

In [26]:
arr = np.array([1, 2, 3,4,5,6,7,8,9,10])
np.random.shuffle(arr)
arr

array([ 8,  2, 10,  3,  1,  4,  7,  6,  9,  5])

In [27]:
cond=arr%2==0
arrCond=arr[cond]
arrCond

array([ 8,  2, 10,  4,  6])